services:
  - type: web
    name: JarvisAI
    runtime: python
    repo: https://github.com/Krishna-yamsalwar/JarvisAI
    branch: main
    envVars:
      - key: CHROMA_DB_PATH
        value: /db/chroma_db
    startCommand: "gunicorn server:app"
    disk:
      name: chromadb-disk
      mountPath: /db/chroma_db
      sizeGB: 1
